### ISSUE TITLE
vars_file is no longer working?

### ISSUE THREAD

**Issue by iuriaranda** [troykinsella/concourse-ansible-playbook-resource#8]
Correct me if I'm wrong, but I think the `out` parameter `vars_file` is being ignored at the moment. Only `vars` is used. Am I just missing something?

If that's the case I think it should be either implemented back, or removed from the documentation.

**Comment by fenech** [comment]
I guess you gave up waiting a while ago :stuck_out_tongue:, but I just ran into this too. In case it's useful to others, my workaround was to use a `load_var` step:

```yml
- load_var: ansible-vars
  file: vars/vars.json
- put: ansible
  params:
    vars: ((.:ansible-vars))
    # etc.
```
